# ICS 2405: Knowledge-Based Systmes
## Linear Combinations, Sums, Dot Products

In [6]:
# import numpy as np

# quantity = np.array([2, 12, 3])
# costs = np.array([12.5, .5, 1.75])
# print(quantity.dot(costs), # dot-product way 1
# np.dot(quantity, costs), # dot-product way 2
# quantity @ costs, # dot-product way 3
# # (new addition to the family!)
# sep='\n')

#### `dot` product

In [7]:
import numpy as np
quantity = np.array([2, 12, 3])
costs = np.array([12.5, .5, 1.75])

print(np.dot(quantity, costs))

36.25

#### weighted averages

In [8]:
values = np.array([10, 20, 30])
weights = np.array([.5, .25, .25])
np.dot(weights, values)

np.float64(17.5)

One special weighted average occurs when the values are the different outcomes of a
random scenario and the weights represent the probabilities of those outcomes. In this
case, the weighted average is called the expected value of that set of outcomes. Here’s a
simple game. Suppose I roll a standard six-sided die and I get $1.00 if the die turns out
odd and I lose $.50 if the die comes up even. Let’s compute a dot product between the
payoffs and the probabilities of each payoff. My expected outcome is to make

In [11]:
payoffs = np.array([1.0, -.5])
probs = np.array([ .5, .5])
np.dot(payoffs, probs)

np.float64(0.25)

### sums of squares

In [16]:
values = np.array([5, -3, 2, 1])
squares = values * values # element-wise multiplication
print(squares, np.sum(squares), sep='\n') # sum of squares. ha!)

[25  9  4  1]
39

#### numpy

In [17]:
values = np.array([5, -3, 2, 1])
np.dot(values, values)

np.int64(39)

### mean squared errors

In [22]:
import pandas as pd
errors = [5, -5, 3.2, -1.1]
display(pd.DataFrame({'ERRORS': error, 'MSE': error ** 2} for error in errors))

   ERRORS    MSE
0     5.0  25.00
1    -5.0  25.00
2     3.2  10.24
3    -1.1   1.21

In [24]:
import pandas as pd

errors = [5, -5, 3.2, -1.1] # list of errors
 
# DataFrame with the errors and their squares
df = pd.DataFrame({'ERRORS': errors, 'MSE': [error ** 2 for error in errors]})
df

   ERRORS    MSE
0     5.0  25.00
1    -5.0  25.00
2     3.2  10.24
3    -1.1   1.21

In [25]:
np.dot(errors, errors)

np.float64(61.45)